footer
Riko07br/pi-sd-frontend pull request #1
Opened 2024-10-18 22:34 UTC by IcaroMoreir4

2024-10-18 23:00 UTC, Riko07br requested changes

2024-10-18 23:00 UTC, Riko07br commented on public/images/facebookIconFooter.svg
Pode remover os icones, pra padronizar usa os do fontsawesome esse é o
`<i class="fa-brands fa-facebook"></i>`

2024-10-18 23:00 UTC, Riko07br commented on public/images/githubIconFooter.svg
Pode remover os icones, pra padronizar usa os do [fontsawesome](https://fontawesome.com/search?o=r&m=free) esse é o
`<i class="fa-brands fa-github"></i>`

2024-10-18 23:00 UTC, Riko07br commented on public/images/linkedinIconFooter.svg
Esse é o `<i class="fa-brands fa-linkedin"></i>`

2024-10-18 23:00 UTC, Riko07br commented on src/app/components/footer/footer.component.html
> +      <a class="text-lg font-bold buzzard-link-footer" href="./">(61) 3213 – 1313</a>
Não usa href, pode usar o `[routerLink]="['/']"` mas nesse caso o número de telefone nem precisa ser link

2024-10-18 23:00 UTC, Riko07br commented on src/styles.css
> +  .hover-icon-grow {
Vou padronizar os demais métodos aqui, mas tenta seguir o padrão `bzd-<local onde vai ser usado>-<descrição>`. Esse dai poderia ser `bzd-footer-icon` já que provavelmente não vamos ter outros ícones no footer

2024-10-21 02:20 UTC, Riko07br requested changes
Lembra de dar uma olhada em todos os comentários e ir marcando o que já foi ajeitado pra não perder a conta das coisas

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/auth/login/login.component.html
> +<!-- <div class="flex justify-center items-center h-full">
Pode remover os códigos comentados quando for submeter, a não ser que seja algo importante

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/auth/login/login.component.html
> +          <p *ngIf="emailValid" class="text-red-500">Email inválido</p>
No momento, login não tem validação então pode remover

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/auth/login/login.component.html
> +          <div *ngIf="passwordValid" class="text-red-500">
No momento, login não tem validação então pode remover

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/auth/register/register.component.html
> +          <p *ngIf="emailValid" class="text-red-500">Email inválido</p>
Para deixar o projeto padronizado, não usa o `*ngIf` usa o 
```
@if(condição){
código que vai aparecer
}
```

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/auth/register/register.component.html
> +          <div *ngIf="passwordValid" class="text-red-500">
Mesma coisa da linha 41

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/auth/register/register.component.html
> +          <p *ngIf="confirmPasswordValid" class="text-red-500">
Mesma coisa da linha 41

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/footer/footer.component.html
> +        >
Ajeitar a formatação de  `<` e `>`

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/footer/footer.component.html
> +        >
Ajeitar a formatação de  `<` e `>`

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/footer/footer.component.html
> +        >
Ajeitar a formatação de  `<` e `>`

2024-10-21 02:20 UTC, Riko07br commented on src/app/components/footer/footer.component.html
> +            ><i class="fa-brands fa-linkedin fa-2x hover-icon-grow"></i></a>
Ajeitar a formatação de  `<` e `>`

2024-10-21 02:20 UTC, Riko07br commented on src/styles.css
> +  }
Como foi discutido na call, essa classe vai ser removida e o estilo vai ser aplicado diretamente no HTML

2024-10-21 02:20 UTC, Riko07br commented on src/styles.css
> +
Como foi discutido na call, essas classes vão ser removidas e o estilo vai ser aplicado diretamente nos HTMLs

2024-10-22 00:20 UTC, IcaroMoreir4 commented on src/styles.css
> +
classes apagadas e colocadas direto no código.

2024-10-22 00:20 UTC, IcaroMoreir4 commented on src/styles.css
> +  }
classes apagadas e colocadas direto no código.

2024-10-22 00:22 UTC, IcaroMoreir4 commented on src/app/components/footer/footer.component.html
> +            ><i class="fa-brands fa-linkedin fa-2x hover-icon-grow"></i></a>
formatei com o plugin que me indicou.

2024-10-22 00:23 UTC, IcaroMoreir4 commented on src/app/components/auth/register/register.component.html
> +          <div *ngIf="passwordValid" class="text-red-500">
fiz com o if, como me foi dito.

2024-10-22 01:27 UTC, Riko07br commented
Ficaram coisas pra ajeitar, mas pra adiantar eu ajeito aqui, vou dar o merge

2024-10-22 01:29 UTC, merged