landing page
Riko07br/pi-sd-frontend pull request #3
Opened 2024-10-22 20:26 UTC by IcaroMoreir4

2024-10-23 01:24 UTC, Riko07br requested changes

2024-10-23 01:24 UTC, Riko07br commented on src/app/components/landing/landing.component.html
> +   class="mt-24 bg-bzd-orange-light flex justify-between items-center px-80">  <!-- Criei essa mt para quando criar o header fixo não cobrir a page -->
O ideal seria colocar isso no `src\app\app.component.html` pra que fosse aplicado a todas as páginas e não só a essa

2024-10-23 01:24 UTC, Riko07br commented on src/app/components/landing/landing.component.html
> +    </button>
Aqui tu pode usar o `<a>` com o `[routerLink]="['/auth', 'register']"`, porque quando o usuário passar o mouse em cima ele vai ver pra onde vai ser redirecionado caso clique.

2024-10-23 17:03 UTC, IcaroMoreir4 commented on src/app/components/landing/landing.component.html
> +   class="mt-24 bg-bzd-orange-light flex justify-between items-center px-80">  <!-- Criei essa mt para quando criar o header fixo não cobrir a page -->
no casso aplicando essa "mt" em todos os componentes?

2024-10-23 17:04 UTC, IcaroMoreir4 commented on src/app/components/landing/landing.component.html
> +    </button>
certo.

2024-10-24 01:42 UTC, Riko07br approved these changes

2024-10-24 01:44 UTC, merged