Perfil, basta olhar o commit "Profile"
Riko07br/pi-sd-frontend pull request #5
Opened 2024-10-26 21:02 UTC by IcaroMoreir4

Deve criar as funções para cada input:
 @if (inputValid) {
      <p class="text-red-500">mensagem de erro.</p>
      }
      
Preferi deixar sem a opção de cartão.

2024-10-27 11:29 UTC, Riko07br requested changes

2024-10-27 11:29 UTC, Riko07br commented on src/app/app.component.html
> +<main class="h-screen flex flex-col mt-24">
Aqui tu já pode colocar o z-index

2024-10-27 11:29 UTC, Riko07br commented on src/app/components/header/header.component.html
> +  class="bg-bzd-orange border-b border-bzd-orange-dark px-24 fixed top-0 left-0 right-0 z-50">
Usa um z-index menor, talvez `z-10` para não cobrir as notificações (toasts)

2024-10-27 11:29 UTC, Riko07br commented on src/app/components/header/header.component.html
> +            Inicio</a>
Lembra de formatar, o mesmo vale pras linhas 31 e 37

2024-10-27 11:29 UTC, Riko07br commented on src/app/components/header/header.component.html
> +        </a>
Seria interessante se desse a aparência de algo clicável

2024-10-27 11:29 UTC, Riko07br commented on src/app/components/header/header.component.html
> +          class="w-full border font-bold p-0.5 rounded-lg text-center text-white border-white hover:border-bzd-orange-dark hover:text-bzd-orange-dark">
Esses botões podem ser substituídos por `bzd-btn-secondary text-white border-white items-center`

2024-10-27 11:29 UTC, Riko07br commented on src/app/components/logged/profile/profile.component.html
> +      <p class="text-red-500">Número já cadastrado.</p>
Caso a gente use essa validação, ela seria feita o servidor, então o erro pode ser um toast. A validação local que pode ser feita aqui é o tamanho do número e se não há letras no meio

2024-10-27 22:08 UTC, IcaroMoreir4 commented on src/app/app.component.html
> +<main class="h-screen flex flex-col mt-24">
não entendi, como o z-index resolveria tal probelma do Margin Top?

2024-10-27 22:09 UTC, IcaroMoreir4 commented on src/app/components/header/header.component.html
> +            Inicio</a>
eu estou formatando usando aquele plugin que me indicou.

2024-10-27 22:17 UTC, IcaroMoreir4 commented on src/app/components/header/header.component.html
> +          class="w-full border font-bold p-0.5 rounded-lg text-center text-white border-white hover:border-bzd-orange-dark hover:text-bzd-orange-dark">
tentei colocar tal estilo mas não deu muito bom, os botões ficaram muito grades:
![image](https://github.com/user-attachments/assets/7fa6637b-434a-4e40-8ee1-f986aa09f01c)

2024-10-27 22:18 UTC, IcaroMoreir4 commented on src/app/components/header/header.component.html
> +          class="w-full border font-bold p-0.5 rounded-lg text-center text-white border-white hover:border-bzd-orange-dark hover:text-bzd-orange-dark">
olha como ficaram usando a estilização que estava antes:
![image](https://github.com/user-attachments/assets/abef84bb-cdf4-4f81-845f-409518533eee)

2024-10-27 22:19 UTC, IcaroMoreir4 commented on src/app/components/logged/profile/profile.component.html
> +      <p class="text-red-500">Número já cadastrado.</p>
então no caso devo apagar tudo de erro e deixar para fazer o toast posteriormente?

2024-10-29 01:54 UTC, Riko07br approved these changes

2024-10-29 01:56 UTC, merged